apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoproject
  labels:
    app: ultrondemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ultrondemo
  template:
    metadata:
      labels:
        app: ultrondemo
    spec:
      containers:
        - name: ultrondemo
          image: demoapp:main-4f8ecf0
          ports:
            - containerPort: 8080