apiVersion: v1
kind: Service
metadata:
  name: ultrondemo
spec:
  selector:
    app.kubernetes.io/name: ultrondemo
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 9376
    - name: https
      protocol: TCP
      port: 443
      targetPort: 9377